# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/westwell/CLionProjects/activity1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/westwell/CLionProjects/activity1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/westwell/CLionProjects/activity1/CMakeFiles /home/westwell/CLionProjects/activity1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/westwell/CLionProjects/activity1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named activity1

# Build rule for target.
activity1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 activity1
.PHONY : activity1

# fast build rule for target.
activity1/fast:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/build
.PHONY : activity1/fast

demos/test_reader.o: demos/test_reader.cpp.o

.PHONY : demos/test_reader.o

# target to build an object file
demos/test_reader.cpp.o:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/demos/test_reader.cpp.o
.PHONY : demos/test_reader.cpp.o

demos/test_reader.i: demos/test_reader.cpp.i

.PHONY : demos/test_reader.i

# target to preprocess a source file
demos/test_reader.cpp.i:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/demos/test_reader.cpp.i
.PHONY : demos/test_reader.cpp.i

demos/test_reader.s: demos/test_reader.cpp.s

.PHONY : demos/test_reader.s

# target to generate assembly for a file
demos/test_reader.cpp.s:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/demos/test_reader.cpp.s
.PHONY : demos/test_reader.cpp.s

src/DataProc.o: src/DataProc.cpp.o

.PHONY : src/DataProc.o

# target to build an object file
src/DataProc.cpp.o:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/src/DataProc.cpp.o
.PHONY : src/DataProc.cpp.o

src/DataProc.i: src/DataProc.cpp.i

.PHONY : src/DataProc.i

# target to preprocess a source file
src/DataProc.cpp.i:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/src/DataProc.cpp.i
.PHONY : src/DataProc.cpp.i

src/DataProc.s: src/DataProc.cpp.s

.PHONY : src/DataProc.s

# target to generate assembly for a file
src/DataProc.cpp.s:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/src/DataProc.cpp.s
.PHONY : src/DataProc.cpp.s

src/DataReader.o: src/DataReader.cpp.o

.PHONY : src/DataReader.o

# target to build an object file
src/DataReader.cpp.o:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/src/DataReader.cpp.o
.PHONY : src/DataReader.cpp.o

src/DataReader.i: src/DataReader.cpp.i

.PHONY : src/DataReader.i

# target to preprocess a source file
src/DataReader.cpp.i:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/src/DataReader.cpp.i
.PHONY : src/DataReader.cpp.i

src/DataReader.s: src/DataReader.cpp.s

.PHONY : src/DataReader.s

# target to generate assembly for a file
src/DataReader.cpp.s:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/src/DataReader.cpp.s
.PHONY : src/DataReader.cpp.s

src/FeatureExtractor.o: src/FeatureExtractor.cpp.o

.PHONY : src/FeatureExtractor.o

# target to build an object file
src/FeatureExtractor.cpp.o:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/src/FeatureExtractor.cpp.o
.PHONY : src/FeatureExtractor.cpp.o

src/FeatureExtractor.i: src/FeatureExtractor.cpp.i

.PHONY : src/FeatureExtractor.i

# target to preprocess a source file
src/FeatureExtractor.cpp.i:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/src/FeatureExtractor.cpp.i
.PHONY : src/FeatureExtractor.cpp.i

src/FeatureExtractor.s: src/FeatureExtractor.cpp.s

.PHONY : src/FeatureExtractor.s

# target to generate assembly for a file
src/FeatureExtractor.cpp.s:
	$(MAKE) -f CMakeFiles/activity1.dir/build.make CMakeFiles/activity1.dir/src/FeatureExtractor.cpp.s
.PHONY : src/FeatureExtractor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... activity1"
	@echo "... demos/test_reader.o"
	@echo "... demos/test_reader.i"
	@echo "... demos/test_reader.s"
	@echo "... src/DataProc.o"
	@echo "... src/DataProc.i"
	@echo "... src/DataProc.s"
	@echo "... src/DataReader.o"
	@echo "... src/DataReader.i"
	@echo "... src/DataReader.s"
	@echo "... src/FeatureExtractor.o"
	@echo "... src/FeatureExtractor.i"
	@echo "... src/FeatureExtractor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

